/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: '#fcf9ef',
          dim: '#dddad0',
          bright: '#fcf9ef',
          container: {
            lowest: '#ffffff',
            low: '#f7f4e9',
            DEFAULT: '#f1eee4',
            high: '#ebe8de',
            highest: '#e5e2d9',
          },
        },
        'on-surface': {
          DEFAULT: '#1c1c16',
          variant: '#45474d',
        },
        'inverse-surface': {
          DEFAULT: '#31312a',
          on: '#f4f1e7',
        },
        outline: {
          DEFAULT: '#75777d',
          variant: '#c5c6cd',
        },
        'surface-tint': '#545e76',
        primary: {
          DEFAULT: '#051125',
          on: '#ffffff',
          container: '#1b263b',
          'on-container': '#828da7',
          fixed: '#d7e2ff',
          'fixed-dim': '#bbc6e2',
          'on-fixed': '#101b30',
          'on-fixed-variant': '#3c475d',
        },
        'inverse-primary': '#bbc6e2',
        secondary: {
          DEFAULT: '#775a19',
          on: '#ffffff',
          container: '#fed488',
          'on-container': '#785a1a',
          fixed: '#ffdea5',
          'fixed-dim': '#e9c176',
          'on-fixed': '#261900',
          'on-fixed-variant': '#5d4201',
        },
        tertiary: {
          DEFAULT: '#1a0f00',
          on: '#ffffff',
          container: '#332306',
          'on-container': '#a28963',
          fixed: '#fcdeb3',
          'fixed-dim': '#dfc299',
          'on-fixed': '#271901',
          'on-fixed-variant': '#574423',
        },
        error: {
          DEFAULT: '#ba1a1a',
          on: '#ffffff',
          container: '#ffdad6',
          'on-container': '#93000a',
        },
        background: '#fcf9ef',
        'on-background': '#1c1c16',
        'surface-variant': '#e5e2d9',
        'ink-blue': '#1b263b',
        'aged-gold': '#c5a059',
        'parchment-base': '#f5f2e8',
        'manuscript-red': '#8b0000',
        'slate-gray': '#757575',
      },
      fontFamily: {
        display: ['"Noto Serif Hebrew"', '"Noto Serif"', 'serif'],
        heading: ['"Noto Serif Hebrew"', '"Noto Serif"', 'serif'],
        body: ['"Hanken Grotesk"', '"Noto Sans Hebrew"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      maxWidth: {
        container: '1120px',
      },
      spacing: {
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
